services:
  - type: web
    name: expiry-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
